#!/bin/bash

if [ $# -ne 1 ]; then
   echo "Usage: $0 <4-digit-integer>"
   exit 1
fi

input=$1

if ! [[ $input =~ ^[0-9]{4}$ ]]; then
   echo "Error: input must be a 4-digit integer"
   exit 1
fi

hash=$(echo -n "$input" | sha256sum | awk '{print $1}')
echo "Hash of $input: $hash"

echo $hash > hash_output.txt
